### PR TITLE
Add helper functions for getting Reports & Markers out of Diagnostics

### PR DESCRIPTION
**Pull request by luc-tielen**
Exposes some helper functions as discussed in #9.

@Mesabloo let me know if I need to add tests etc. They are simple functions, but maybe you want tests anyway? In the meantime I will try building my LSP using this branch.

### CODE REVIEW

**Comment by Mesabloo** [comment]
Don't worry about testing those functions. They are small enough not to be tested (the whole codebase isn't properly tested anyways). :)

Most of the changes look good to me. I am just a bit hesitant about the `markersOf` function. 
Doing so, we should also have one function per type of data which can be unpacked from the `Report` (one for the markers, one for the message, one for the notes, etc). With simple pattern synonyms, we should be able to have a very simple API (which would not leak the internal representation) such as, for example
```haskell
pattern Warn, Err :: forall msg. Maybe msg -> msg -> [(Position, Marker msg)] -> [Note msg] -> Report msg
pattern Warn errCode msg reports notes = Report False errCode msg reports notes
pattern Err errCode msg reports notes = Report True errCode msg reports notes
```
Now, whenever we need some information, we can have it however we like it (either both the message and the reports, or also the note, and more importantly the fact that it is a warning/error).
Plus we didn't leak the private internal representation, as we can always apply a function to `reports` and `notes` to convert to the internal representation (in this case, those are already lists so it's just the identity).
I don't know if this piece of code works, but something along those lines should.
And we also get free pattern matching using `case` thanks to that. :D

**Comment by luc-tielen** [comment]
@Mesabloo Yeah it works, but I had to change the implicit whole module export to an explicit one :man_shrugging:.
As a bonus, I could export the patterns as the only "constructors" for `Report`.

Code seems to build, but this is with default flags configured.
Tests seem to pass, but idk if a manual check needs to be done as well?

**Comment by Mesabloo** [comment]
> Yeah it works, but I had to change the implicit whole module export to an explicit one 🤷‍♂️.

```haskell
module Error.Diagnose.Report.Internal
  ( Marker (..)
  , Note (..)
  , Report(.., Warn, Err)
  , err
  , errorToWarning
  , warn
  , warningToError
  , FileMap
  , prettyReport
  ) where
  -- ...
```
You can also do `module Error.Diagnose.Report.Internal (module Error.Diagnose.Report.Internal, Report (.., Warn, Err)) where` (similar to what I did in the `Error.Diagnose.Diagnostic.Internal` module, see [here](https://github.com/Mesabloo/diagnose/blob/f8badb4d8c11034c52cf7af6cec2879406cea4ed/src/Error/Diagnose/Diagnostic/Internal.hs#L16)).

-----------------

Everything else looks good to me! 😄

**Comment by Mesabloo** [comment]
Also, I believe I had references to both `warn` and `err` in the documentation for the module `Error.Diagnose`.
This may need to be fixed to.

**Comment by luc-tielen** [comment]
> > Yeah it works, but I had to change the implicit whole module export to an explicit one man_shrugging.
> 
> ```haskell
> module Error.Diagnose.Report.Internal
>   ( Marker (..)
>   , Note (..)
>   , Report(.., Warn, Err)
>   , err
>   , errorToWarning
>   , warn
>   , warningToError
>   , FileMap
>   , prettyReport
>   ) where
>   -- ...
> ```
> 
> You can also do `module Error.Diagnose.Report.Internal (module Error.Diagnose.Report.Internal, Report (.., Warn, Err)) where` (similar to what I did in the `Error.Diagnose.Diagnostic.Internal` module, see [here](https://github.com/Mesabloo/diagnose/blob/f8badb4d8c11034c52cf7af6cec2879406cea4ed/src/Error/Diagnose/Diagnostic/Internal.hs#L16)).
> 
> Everything else looks good to me! :smile:

Ah yes, much simpler. Thanks!

> Also, I believe I had references to both `warn` and `err` in the documentation for the module `Error.Diagnose`. This may need to be fixed to.

Couldn't find any using grep? Maybe no references?

**Comment by Mesabloo** [comment]
> Couldn't find any using grep? Maybe no references?
Only there https://github.com/Mesabloo/diagnose/blob/f8badb4d8c11034c52cf7af6cec2879406cea4ed/src/Error/Diagnose.hs#L74-L92

And in the compatibility layers for (mega)parsec too  https://github.com/Mesabloo/diagnose/blob/f8badb4d8c11034c52cf7af6cec2879406cea4ed/src/Error/Diagnose/Compat/Parsec.hs#L50 https://github.com/Mesabloo/diagnose/blob/f8badb4d8c11034c52cf7af6cec2879406cea4ed/src/Error/Diagnose/Compat/Megaparsec.hs#L58 

Apart from that, it should be everything that needs to be changed. :)

**Comment by luc-tielen** [comment]
@Mesabloo Ok, my grep didn't cover everything. This should be everything now!

(I had already fixed the parsec related files.)

**Comment by Mesabloo** [comment]
> (I had already fixed the parsec related files.)

Ah sorry, I completely missed it!

----------------------

> This should be everything now!

Thank you very much for your contributions! I'm merging this now but I'll publish a new version to hackage later. In the meantime, you should be able to use the `master` branch. 😃

**Comment by Mesabloo** [comment]
@luc-tielen Version 2.4.0 is [live](https://hackage.haskell.org/package/diagnose-2.4.0)! :tada:

**Pull request merged**
